// /src/components/dashboard/RecruitmentForm.tsx
'use client';
import { useState, useEffect } from 'react';
import createClient from '@/api/client';
import { Recruitment } from '@/lib/types/supabase';

interface RecruitmentFormProps {
    table: string; // Should be "recruitment"
    initialData: Recruitment | null;
    onSuccess: (action: 'inserted' | 'updated') => void;
    onCancel: () => void;
}

// Function to safely initialize form state
const initializeFormState = (data: Recruitment | null): Partial<Recruitment> => ({
    full_name: data?.full_name || '',
    registration_number: data?.registration_number || '',
    email_address: data?.email_address || '',
    phone_number: data?.phone_number || '',
    date_of_birth: data?.date_of_birth || '',
    gender: data?.gender || '',
    branch_department: data?.branch_department || '',
    course_year: data?.course_year || '',
    participated_before: data?.participated_before || false, // boolean default
    why_join_optimus: data?.why_join_optimus || '',
    whatsapp_number: data?.whatsapp_number || '',
    residence: data?.residence || '',
    areas_of_interest: data?.areas_of_interest || [],
});

export default function RecruitmentForm({ table, initialData, onSuccess, onCancel }: RecruitmentFormProps) {
    const [formData, setFormData] = useState<Partial<Recruitment>>(initializeFormState(initialData));
    const [loading, setLoading] = useState(false);
    const supabase = createClient;
    
    const isEditing = !!initialData;

    useEffect(() => {
        setFormData(initializeFormState(initialData));
    }, [initialData]);

    const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
        const { name, value, type } = e.target;
        
        // Special handling for boolean checkbox/radio
        if (type === 'radio' && name === 'participated_before') {
            setFormData(prev => ({ ...prev, [name]: value === 'true' }));
        } else {
            setFormData(prev => ({ ...prev, [name]: value }));
        }
    };
    
    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setLoading(true);

        const dataToSubmit = { ...formData };
        
        // Ensure ID is available for update
        if (isEditing && !initialData?.id) {
             alert('Error: Cannot update without an ID.');
             setLoading(false);
             return;
        }

        let supabaseResponse;
        if (isEditing) {
            // UPDATE Logic (Note: ID is int4 here)
            supabaseResponse = await supabase
                .from(table)
                .update(dataToSubmit)
                .eq('id', initialData!.id); 
        } else {
            // INSERT Logic (ID will be auto-generated by DB)
            supabaseResponse = await supabase
                .from(table)
                .insert([dataToSubmit]);
        }

        setLoading(false);
        if (supabaseResponse.error) {
            console.error('Submission Error:', supabaseResponse.error);
            alert(`Error saving data: ${supabaseResponse.error.message}`);
        } else {
            onSuccess(isEditing ? 'updated' : 'inserted');
        }
    };

    return (
        <div className="p-6">
            <h2 className="text-2xl font-bold mb-6 text-green-400 border-b border-gray-700 pb-2">
                {isEditing ? `Edit Recruitment Entry (ID: ${initialData?.id})` : 'Add New Recruitment Entry'}
            </h2>
            <form onSubmit={handleSubmit} className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {/* Row 1: Name and Email */}
                <div>
                    <label className="block text-sm font-medium text-gray-300">Full Name *</label>
                    <input type="text" name="full_name" value={formData.full_name} onChange={handleChange} required className="mt-1 block w-full bg-gray-800 border border-gray-700 rounded-md shadow-sm p-2 text-white" />
                </div>
                <div>
                    <label className="block text-sm font-medium text-gray-300">Email Address *</label>
                    <input type="email" name="email_address" value={formData.email_address} onChange={handleChange} required className="mt-1 block w-full bg-gray-800 border border-gray-700 rounded-md shadow-sm p-2 text-white" />
                </div>

                {/* Row 2: Reg Number and Phone */}
                <div>
                    <label className="block text-sm font-medium text-gray-300">Registration Number *</label>
                    <input type="text" name="registration_number" value={formData.registration_number} onChange={handleChange} required className="mt-1 block w-full bg-gray-800 border border-gray-700 text-white rounded-md shadow-sm p-2" />
                </div>
                <div>
                    <label className="block text-sm font-medium text-gray-300">Phone Number *</label>
                    <input type="tel" name="phone_number" value={formData.phone_number} onChange={handleChange} required className="mt-1 block w-full bg-gray-800 border border-gray-700 text-white rounded-md shadow-sm p-2" />
                </div>
                
                {/* Row 3: DOB and Gender */}
                <div>
                    <label className="block text-sm font-medium text-gray-300">Date of Birth *</label>
                    <input type="date" name="date_of_birth" value={formData.date_of_birth} onChange={handleChange} required className="mt-1 block w-full bg-gray-800 border border-gray-700 text-white rounded-md shadow-sm p-2" />
                </div>
                <div>
                    <label className="block text-sm font-medium text-gray-300">Gender *</label>
                    <select name="gender" value={formData.gender} onChange={handleChange} required className="mt-1 block w-full bg-gray-800 border border-gray-700 text-white rounded-md shadow-sm p-2">
                        <option value="">Select Gender</option>
                        <option value="Male">Male</option>
                        <option value="Female">Female</option>
                        <option value="Other">Other</option>
                    </select>
                </div>

                {/* Row 4: Branch and Course */}
                <div>
                    <label className="block text-sm font-medium text-gray-300">Branch/Department *</label>
                    <input type="text" name="branch_department" value={formData.branch_department} onChange={handleChange} required className="mt-1 block w-full bg-gray-800 border border-gray-700 text-white rounded-md shadow-sm p-2" />
                </div>
                <div>
                    <label className="block text-sm font-medium text-gray-300">Course/Year *</label>
                    <input type="text" name="course_year" value={formData.course_year} onChange={handleChange} required className="mt-1 block w-full bg-gray-800 border border-gray-700 text-white rounded-md shadow-sm p-2" />
                </div>
                
                {/* Row 5: Participated Before (Boolean) */}
                <div className="col-span-2">
                    <label className="block text-sm font-medium text-gray-300 mb-1">Participated Before? *</label>
                    <div className="flex space-x-4">
                        <label className="inline-flex items-center">
                            <input type="radio" name="participated_before" value="true" checked={formData.participated_before === true} onChange={handleChange} required className="form-radio text-green-600" />
                            <span className="ml-2 text-gray-300">Yes</span>
                        </label>
                        <label className="inline-flex items-center">
                            <input type="radio" name="participated_before" value="false" checked={formData.participated_before === false} onChange={handleChange} required className="form-radio text-green-600" />
                            <span className="ml-2 text-gray-300">No</span>
                        </label>
                    </div>
                </div>

                {/* Row 6: Why Join Optimus (Textarea) */}
                <div className="col-span-2">
                    <label className="block text-sm font-medium text-gray-300">Why Join Optimus? *</label>
                    <textarea name="why_join_optimus" value={formData.why_join_optimus} onChange={handleChange} rows={3} required className="mt-1 block w-full bg-gray-800 border border-gray-700 text-white rounded-md shadow-sm p-2"></textarea>
                </div>
                
                {/* Optional Fields (Example: WhatsApp Number) */}
                <div>
                    <label className="block text-sm font-medium text-gray-300">WhatsApp Number (Optional)</label>
                    <input type="tel" name="whatsapp_number" value={formData.whatsapp_number} onChange={handleChange} className="mt-1 block w-full bg-gray-800 border border-gray-700 text-white rounded-md shadow-sm p-2" />
                </div>
                
                {/* Action Buttons */}
                <div className="col-span-2 flex justify-end space-x-3 mt-4">
                    <button type="button" onClick={onCancel} className="px-4 py-2 border border-gray-700 rounded-md text-gray-300 hover:bg-gray-700">
                        Cancel
                    </button>
                    <button type="submit" disabled={loading} className="px-4 py-2 bg-green-600 text-white font-bold rounded-md shadow-md hover:bg-green-700 disabled:bg-green-400">
                        {loading ? 'Saving...' : (isEditing ? 'Update Entry' : 'Create Entry')}
                    </button>
                </div>
            </form>
        </div>
    );
}