// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://whcoayuuwebcpbgyesej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndoY29heXV1d2ViY3BiZ3llc2VqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMDQ4NTAsImV4cCI6MjA3MDY4MDg1MH0.ILDUqhQbMKa3VbuoFF5t_TFe9sr8rV6DdhZkwDcSZTA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});